### ISSUE TITLE
README : Wrong instruction at 8.

### ISSUE THREAD

**Issue by Darkness4** [fireship-io/git-sticker#131]
Hello,

Isn't `git push origin ilikefreestuff` instead of `git push origin mysticker` (like in your video) ?

**Comment by jj0309** [comment]
It depends on how you named your branch.

**Comment by Darkness4** [comment]
@jj0309 
Yes, of course.

But if we strictly follow the instructions. Instruction 4: 

> 4.  create a new branch with `git checkout -b ilikefreestuff`

implies that the branch must be named `ilikefreestuff`.

**Comment by Janbuller** [comment]
@Darkness4 Just a small theory (might be completely wrong), he might have done it, to make sure people understood why and were not just copying commands.

**Comment by aromalanil** [comment]
I think it must be `git push origin <name_of_your_branch>` or something

**Comment by alexako** [comment]
@Darkness4 You are definitely correct. I'm just choosing to believe it was deliberate because it's funnier. But in all seriousness, step 8 should be `git push origin ilikefreestuff` because the branch name actually exists (which `mysticker` does not if one strictly follows the instructions).

**Comment by TFisicaro** [comment]
Do you only get a sticker if you strictly follow the instructions?

**Comment by Darkness4** [comment]
@TFisicaro I don't know. I don't think the name of the new branch "ilikefreestuff" matters.

But I think it's best to follow the guidelines.

However, this rule doesn't seem to be negligible:

> Your commit must contain **only 1 file**. Verify that you did not change any existing code before making your PR. Do not commit any automatically modified yarn or package-json.lock files.

Because, if you run the script, at the end, you'll get : 

```txt
Your PR should have exactly 1 new file. It may be rejected if multiple files are modified. 
```

**Comment by robe007** [comment]
On the 7th step, I made:

`git add stickers/<your-github-username>.txt` to only add that file to the PR.

This is because when I ran `npm install`, the file `package-json.lock` was modified too. If you run `git status` you will see it.

**Comment by justlester** [comment]
If your package-json.lock was modified just revert it back to its original commit before you commit.

**Comment by robe007** [comment]
Yes. That's other way.

If you want to do `git add .`, you need to do first: `git checkout -- package-lock.json`. As I said before, this file gets modified when you do: `npm install`.

Why the `package-lock.json` file gets modified? Well, because it's name property is `git-lucky`, and when you do `npm install`, takes the name property from `package.json` that is `git-sticker`. =)

**Comment by Riz-waan** [comment]
I think he did that on purpose 😂
