### ISSUE TITLE
package-lock.json changed with PR #138

### ISSUE THREAD

**Issue by TheGLander** [fireship-io/git-sticker#700]
I guess you didn't closely check the PR's, since one of them managed to rename the package name in `package-lock.json`...

**Comment by jakubkoje** [comment]
Same :/

**Comment by HexF** [comment]
Hi,
I inspected the changes and the only thing that changed was the EOF byte, maybe the IDE just changed it?
Doesn't seem like a security risk as no packages were updates

**Comment by MartinNemi03** [comment]
Yep, it was an automated thing added by my IDE (VS Code), while I browsed the files in a hurry. I hate, that it happened and that I can't do anything about it anymore.

**Comment by HexF** [comment]
Issue can be closed as its not a security threat
