### ISSUE TITLE
Dependencies For JS not automatically installed

### ISSUE THREAD

**Issue by ghost** [fireship-io/git-sticker#821]
Hi @codediodeio
Dependencies Chalk, inquirer and Node-RSA are not automatically installed on Windows

**Comment by SmintGaming** [comment]
Dependencies chalk, inquirer and Node-RSA not automatically installed

**Comment by elasticskyx** [comment]
If you get error when executing npm start, then check if the dependencies are installed.
$> npm install -g npm-check-updates
$> ncu -u
$> npm install

**Comment by ghost** [comment]
It Doesn't Say A Thing About Dependencies On My Linux Machine But It Throws Error After Error On My Windows Laptop
